spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cv_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  application:
    name: curriculum-vitae-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true



